# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_args_RestClient__initialize <- function(keys, base_url, async, time_source, time_endpoint, time_field, body_format, user_agent, max_tries, throttle_rate) {
  if (!is.null(keys)) {
    assert_list(keys)
  }
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  assert_scalar_character(time_source)
  assert_value_in_set(time_source, c("local", "server"))
  if (!is.null(time_endpoint)) {
    assert_scalar_character(time_endpoint)
  }
  assert_scalar_character(time_field)
  assert_scalar_character(body_format)
  assert_value_in_set(body_format, c("json", "query", "none", "raw"))
  assert_scalar_character(user_agent)
  assert_scalar_count(max_tries)
  assert_between(max_tries, lower = 1)
  if (!is.null(throttle_rate)) {
    assert_scalar_double(throttle_rate)
    assert_between(throttle_rate, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  }
  return(invisible(NULL))
}

assert_return_RestClient__initialize <- function(value) {
  assert_class(value, "RestClient")
  return(value)
}

assert_args_StreamClient__initialize <- function(url, auto_reconnect, max_reconnects, backoff_cap, proactive_reconnect, stale_timeout, keepalive) {
  assert_scalar_character(url)
  assert_scalar_logical(auto_reconnect)
  assert_scalar_double(max_reconnects)
  assert_scalar_double(backoff_cap)
  assert_between(backoff_cap, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  if (!is.null(proactive_reconnect)) {
    assert_scalar_double(proactive_reconnect)
    assert_between(proactive_reconnect, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  }
  if (!is.null(stale_timeout)) {
    assert_scalar_double(stale_timeout)
    assert_between(stale_timeout, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  }
  assert_scalar_double(keepalive)
  assert_between(keepalive, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_StreamClient__initialize <- function(value) {
  assert_class(value, "StreamClient")
  return(value)
}

assert_args_StreamClient__on <- function(event, handler) {
  assert_scalar_character(event)
  assert_function(handler)
  return(invisible(NULL))
}

assert_return_StreamClient__on <- function(value) {
  assert_class(value, "StreamClient")
  return(value)
}

assert_return_StreamClient__connect <- function(value) {
  assert_class(value, "StreamClient")
  return(value)
}

assert_args_StreamClient__send <- function(message) {
  assert_scalar_character(message)
  return(invisible(NULL))
}

assert_return_StreamClient__send <- function(value) {
  assert_class(value, "StreamClient")
  return(value)
}

assert_args_StreamClient__run <- function(timeout) {
  assert_scalar_double(timeout)
  assert_between(timeout, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_StreamClient__run <- function(value) {
  assert_class(value, "StreamClient")
  return(value)
}

assert_return_StreamClient__close <- function(value) {
  assert_class(value, "StreamClient")
  return(value)
}

assert_return_StreamClient__is_open <- function(value) {
  assert_scalar_logical(value)
  return(value)
}

assert_args_hmac_query_sign <- function(req, keys, get_timestamp_ms, api_key_header, signature_param, timestamp_param) {
  assert_class(req, "httr2_request")
  assert_list(keys)
  if (!is.null(get_timestamp_ms)) {
    assert_function(get_timestamp_ms)
  }
  assert_scalar_character(api_key_header)
  assert_scalar_character(signature_param)
  assert_scalar_character(timestamp_param)
  return(invisible(NULL))
}

assert_return_hmac_query_sign <- function(value) {
  assert_class(value, "httr2_request")
  return(value)
}

assert_args_to_snake_case <- function(names) {
  assert_character(names)
  assert_no_missing_values(names)
  return(invisible(NULL))
}

assert_return_to_snake_case <- function(value) {
  assert_character(value)
  assert_no_missing_values(value)
  return(value)
}

assert_args_coalesce_null <- function(x, default) {
  return(invisible(NULL))
}

assert_return_coalesce_null <- function(value) {
  return(value)
}

assert_args_num_or_na <- function(x) {
  return(invisible(NULL))
}

assert_return_num_or_na <- function(value) {
  assert_double(value)
  assert_length(value, 1L)
  return(value)
}

assert_args_chr_or_na <- function(x) {
  return(invisible(NULL))
}

assert_return_chr_or_na <- function(value) {
  assert_character(value)
  assert_length(value, 1L)
  return(value)
}

assert_args_lgl_or_na <- function(x) {
  return(invisible(NULL))
}

assert_return_lgl_or_na <- function(value) {
  assert_logical(value)
  assert_length(value, 1L)
  return(value)
}

assert_args_nth_num <- function(x, i) {
  assert_list(x)
  assert_scalar_count(i)
  assert_between(i, lower = 1)
  return(invisible(NULL))
}

assert_return_nth_num <- function(value) {
  assert_double(value)
  assert_length(value, 1L)
  return(value)
}

assert_args_nth_chr <- function(x, i) {
  assert_list(x)
  assert_scalar_count(i)
  assert_between(i, lower = 1)
  return(invisible(NULL))
}

assert_return_nth_chr <- function(value) {
  assert_character(value)
  assert_length(value, 1L)
  return(value)
}

assert_args_as_dt_row <- function(x) {
  if (!is.null(x)) {
    assert_list(x)
  }
  return(invisible(NULL))
}

assert_return_as_dt_row <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_as_dt_list <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_as_dt_list <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_coerce_cols <- function(dt, cols, fn) {
  assert_class(dt, "data.table")
  assert_character(cols)
  assert_no_missing_values(cols)
  assert_function(fn)
  return(invisible(NULL))
}

assert_return_coerce_cols <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_collapse_string_array_fields <- function(x, fields) {
  assert_list(x)
  assert_character(fields)
  assert_no_missing_values(fields)
  return(invisible(NULL))
}

assert_return_collapse_string_array_fields <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_then_or_now <- function(x, fn, is_async) {
  assert_function(fn)
  assert_scalar_logical(is_async)
  return(invisible(NULL))
}

assert_return_then_or_now <- function(value) {
  return(value)
}

assert_args_parse_json_response <- function(resp) {
  assert_class(resp, "httr2_response")
  return(invisible(NULL))
}

assert_return_parse_json_response <- function(value) {
  return(value)
}

assert_args_fetch_server_time_ms <- function(base_url, time_endpoint, field) {
  assert_scalar_character(base_url)
  assert_scalar_character(time_endpoint)
  assert_scalar_character(field)
  return(invisible(NULL))
}

assert_return_fetch_server_time_ms <- function(value) {
  assert_scalar_double(value)
  return(value)
}

assert_return_next_nonce <- function(value) {
  assert_scalar_double(value)
  return(value)
}

assert_args_build_request <- function(base_url, endpoint, method, query, body, keys, sign, parse_envelope, body_format, raw_content_type, .perform, .parser, is_async, timeout, user_agent, max_tries, throttle_rate, ctx) {
  assert_scalar_character(base_url)
  assert_scalar_character(endpoint)
  assert_scalar_character(method)
  assert_list(query)
  if (!is.null(body)) {
    assert_any_of(
      body,
      function(.x) {
        assert_list(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      },
      function(.x) {
        assert_raw(.x)
      }
    )
  }
  if (!is.null(keys)) {
    assert_list(keys)
  }
  if (!is.null(sign)) {
    assert_function(sign)
  }
  assert_function(parse_envelope)
  assert_scalar_character(body_format)
  assert_value_in_set(body_format, c("json", "query", "none", "raw"))
  assert_scalar_character(raw_content_type)
  assert_function(.perform)
  assert_function(.parser)
  assert_scalar_logical(is_async)
  assert_scalar_double(timeout)
  assert_between(timeout, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_character(user_agent)
  assert_scalar_count(max_tries)
  assert_between(max_tries, lower = 1)
  if (!is.null(throttle_rate)) {
    assert_scalar_double(throttle_rate)
    assert_between(throttle_rate, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  }
  assert_list(ctx)
  return(invisible(NULL))
}

assert_return_build_request <- function(value) {
  return(value)
}

assert_args_ws_backoff_delay <- function(attempt, cap_seconds) {
  assert_scalar_count(attempt)
  assert_between(attempt, lower = 1)
  assert_scalar_double(cap_seconds)
  assert_between(cap_seconds, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_ws_backoff_delay <- function(value) {
  assert_scalar_double(value)
  assert_between(value, lower = 1, upper = Inf, upper_inclusive = FALSE)
  return(value)
}

assert_args_ws_file_sink <- function(con) {
  assert_class(con, "connection")
  return(invisible(NULL))
}

assert_return_ws_file_sink <- function(value) {
  assert_function(value)
  return(value)
}

assert_args_env_or <- function(var, default) {
  assert_scalar_character(var)
  assert_scalar_character(default)
  return(invisible(NULL))
}

assert_return_env_or <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_url_getter <- function(var, default) {
  assert_scalar_character(var)
  assert_scalar_character(default)
  return(invisible(NULL))
}

assert_return_url_getter <- function(value) {
  assert_function(value)
  return(value)
}

assert_args_load_keys <- function(spec, warn) {
  assert_list(spec)
  assert_scalar_logical(warn)
  return(invisible(NULL))
}

assert_return_load_keys <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_epoch_to_datetime <- function(value, unit) {
  assert_double(value)
  assert_no_missing_values(value)
  assert_scalar_character(unit)
  assert_value_in_set(unit, c("ms", "ns", "s"))
  return(invisible(NULL))
}

assert_return_epoch_to_datetime <- function(value) {
  assert_class(value, "POSIXct")
  return(value)
}

assert_args_datetime_to_epoch <- function(datetime, unit) {
  assert_class(datetime, "POSIXct")
  assert_scalar_character(unit)
  assert_value_in_set(unit, c("ms", "ns", "s"))
  return(invisible(NULL))
}

assert_return_datetime_to_epoch <- function(value) {
  assert_double(value)
  assert_no_missing_values(value)
  return(value)
}

assert_args_ms_to_datetime <- function(ms) {
  assert_double(ms)
  assert_no_missing_values(ms)
  return(invisible(NULL))
}

assert_return_ms_to_datetime <- function(value) {
  assert_class(value, "POSIXct")
  return(value)
}

assert_args_datetime_to_ms <- function(datetime) {
  assert_class(datetime, "POSIXct")
  return(invisible(NULL))
}

assert_return_datetime_to_ms <- function(value) {
  assert_double(value)
  assert_no_missing_values(value)
  return(value)
}

